workflows:
  android-cordova:
    name: Android (Cordova)
    environment:
      node: 18.18.2
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $HOME/.npm
        - node_modules
    scripts:
      - name: Instalar dependencias
        script: |
          npm ci || true
          npm i -g cordova
      - name: Preparar Android
        script: |
          cordova platform rm android || true
          cordova platform add android
          cordova prepare android
      - name: Compilar APK/AAB (release, sin firma)
        script: |
          cd platforms/android
          ./gradlew assembleRelease
          ./gradlew bundleRelease
    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk
      - platforms/android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - astorstepapp@gmail.com
