workflows:
  android_capacitor_debug:
    name: Android (Capacitor) – Debug APK
    environment:
      node: 18
    scripts:
      - name: Seleccionar Java 17 (macOS) y configurar Gradle
        script: |
          # JDK 17 correcto en macOS (evita rutas de Linux)
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          echo "JAVA_HOME=$JAVA_HOME"
          java -version

          # Forzar a Gradle a usar esta JDK y permitir descarga de SDK
          echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties
          echo "android.builder.sdkDownload=true" >> android/gradle.properties

      - name: Instalar dependencias
        script: |
          npm ci

      - name: Aceptar licencias (solo si AGP las pide)
        script: |
          yes | "$JAVA_HOME/bin/javac" -version >/dev/null 2>&1 || true
          # AGP gestionará descargas; este paso suele no ser necesario

      - name: Sincronizar Capacitor (genera/actualiza ./android)
        script: |
          npx cap sync android

      - name: Compilar APK debug
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $CM_BUILD_DIR/node_modules
