workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 20.11.1
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    scripts:
      - npm install -g @capacitor/cli
      - npm install
      - npx cap sync
      - npx cap copy android
      # 🔥 Reemplazar cualquier 21 por 17 en TODOS los gradle
      - find . -name "*.gradle" -type f -exec sed -i 's/21/17/g' {} +
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - astorstepapp@gmail.com

  build-ios:
    name: Build iOS IPA
    environment:
      node: 20.11.1
      xcode: 15.0 
    scripts:
      - npm install -g @capacitor/cli
      - npm install
      - npx cap sync
      - npx cap copy ios
      - cd ios && xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos
    artifacts:
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - astorstepapp@gmail.com
