workflows:
  android_capacitor_debug:
    name: Android (Capacitor) – Debug APK
    environment:
      node: 18
    scripts:
      - name: Instalar dependencias
        script: |
          npm ci
      - name: Sincronizar Capacitor (genera/actualiza ./android)
        script: |
          npx cap sync android
      - name: Compilar APK debug con Gradle
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
