workflows:
  build-android:
    name: Build Android APK
    environment:
      node: 20.11.1
    scripts:
      - npm install -g @capacitor/cli
      - npm install
      - npx cap sync
      - npx cap copy android
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - astorstepapp@gmail.com

  build-ios:
    name: Build iOS IPA
    environment:
      node: 20.11.1
    scripts:
      - npm install -g @capacitor/cli
      - npm install
      - npx cap sync
      - npx cap copy ios
      - cd ios && xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos
    artifacts:
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - astorstepapp@gmail.com
