workflows:
  android_capacitor_debug:
    name: Android (Capacitor) – Debug APK
    max_build_duration: 60
    environment:
      java: 17
      vars:
        CI: "true"
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $FCI_BUILD_DIR/node_modules
        - $FCI_BUILD_DIR/android/.gradle
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    scripts:
      - name: Instalar Node y dependencias
        script: |
          set -e
          if ! command -v node >/dev/null 2>&1; then
            . $HOME/.nvm/nvm.sh
            nvm install 18
            nvm use 18
          fi
          node -v
          npm -v
          npm ci

      - name: Sincronizar Capacitor (genera/actualiza ./android)
        script: |
          npx --yes @capacitor/cli sync android

      - name: Asegurar Java 17 en Gradle
        script: |
          echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties
          echo "Usando JAVA_HOME=$JAVA_HOME"

      - name: Compilar APK debug
        script: |
          cd android
          ./gradlew clean assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
